export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const CREATE_ADDRESS_SUCCEEDED = 'CREATE_ADDRESS_SUCCEEDED';

export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const DELETE_ADDRESS_SUCCEEDED = 'DELETE_ADDRESS_SUCCEEDED';

export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const FETCH_ADDRESSES_SUCCEEDED = 'FETCH_ADDRESSES_SUCCEEDED';
