export const CREATE_ATTACHMENT = 'CREATE_ATTACHMENT';
export const CREATE_ATTACHMENT_SUCCEEDED = 'CREATE_ATTACHMENT_SUCCEEDED';
export const CREATE_ATTACHMENT_FAIL = 'CREATE_ATTACHMENT_FAIL';

export const UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT';
export const UPDATE_ATTACHMENT_SUCCEEDED = 'UPDATE_ATTACHMENT_SUCCEEDED';
export const UPDATE_ATTACHMENT_FAIL = 'UPDATE_ATTACHMENT_FAIL';

export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT';
export const DELETE_ATTACHMENT_SUCCEEDED = 'DELETE_ATTACHMENT_SUCCEEDED';
export const DELETE_ATTACHMENT_FAIL = 'DELETE_ATTACHMENT_FAIL';
