export const CREATE_BANK = 'CREATE_BANK';
export const CREATE_BANK_SUCCEEDED = 'CREATE_BANK_SUCCEEDED';

export const DELETE_BANK = 'DELETE_BANK';
export const DELETE_BANK_SUCCEEDED = 'DELETE_BANK_SUCCEEDED';

export const FETCH_BANK = 'FETCH_BANK';
export const FETCH_BANK_SUCCEEDED = 'FETCH_BANK_SUCCEEDED';
