export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_SUCCEEDED = 'CREATE_CARD_SUCCEEDED';

export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_SUCCEEDED = 'DELETE_CARD_SUCCEEDED';

export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CARDS_SUCCEEDED = 'FETCH_CARDS_SUCCEEDED';
