export const FETCH_CART = 'FETCH_CART';
export const FETCH_CART_SUCCEEDED = 'FETCH_CART_SUCCEEDED';
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL';

export const CREATE_CART = 'CREATE_CART';
export const CREATE_CART_SUCCEEDED = 'CREATE_CART_SUCCEEDED';
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_SUCCEEDED = 'UPDATE_CART_SUCCEEDED';
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL';

export const DELETE_CART = 'DELETE_CART';
export const DELETE_CART_SUCCEEDED = 'DELETE_CART_SUCCEEDED';
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL';

export const UPDATE_CART_PRODUCTS = 'UPDATE_CART_PRODUCTS';
