export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCEEDED = 'CREATE_EVENT_SUCCEEDED';

export const FETCH_EVENT = 'FETCH_EVENT';
export const FETCH_EVENT_SUCCEEDED = 'FETCH_EVENT_SUCCEEDED';

export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_SUCCEEDED = 'UPDATE_EVENT_SUCCEEDED';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCEEDED = 'FETCH_EVENTS_SUCCEEDED';
