export const FETCH_HIGHLIGHT = 'FETCH_HIGHLIGHT';
export const FETCH_HIGHLIGHT_SUCCEEDED = 'FETCH_HIGHLIGHT_SUCCEEDED';

export const FETCH_DISABILITIES = 'FETCH_DISABILITIES';
export const FETCH_DISABILITIES_SUCCEEDED = 'FETCH_DISABILITIES_SUCCEEDED';

export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_ROLES_SUCCEEDED = 'FETCH_ROLES_SUCCEEDED';
