export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCEEDED = 'CREATE_ORDER_SUCCEEDED';

export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ORDER_SUCCEEDED = 'FETCH_ORDER_SUCCEEDED';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCEEDED = 'UPDATE_ORDER_SUCCEEDED';

export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCEEDED = 'CANCEL_ORDER_SUCCEEDED';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCEEDED = 'FETCH_ORDERS_SUCCEEDED';

export const UPDATE_ORDER_ID = 'UPDATE_ORDER_ID';
