export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_SUCCEEDED = 'CREATE_REVIEW_SUCCEEDED';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';

export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const FETCH_REVIEWS_SUCCEEDED = 'FETCH_REVIEWS_SUCCEEDED';
export const FETCH_REVIEWS_FAIL = 'FETCH_REVIEWS_FAIL';
