export const FETCH_SUB_CATEGORY = 'FETCH_SUB_CATEGORY';
export const FETCH_SUB_CATEGORY_SUCCEEDED = 'FETCH_SUB_CATEGORY_SUCCEEDED';

export const FETCH_SUB_CATEGORIES = 'FETCH_SUB_CATEGORIES';
export const FETCH_SUB_CATEGORIES_SUCCEEDED = 'FETCH_SUB_CATEGORIES_SUCCEEDED';
