export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const REMOVE_FLASH_MESSAGE = 'REMOVE_FLASH_MESSAGE';
