export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCEEDED = 'UPDATE_USER_SUCCEEDED';

export const REQUEST_SELLER = 'REQUEST_SELLER';
export const REQUEST_SELLER_SUCCEEDED = 'REQUEST_SELLER_SUCCEEDED';
